sudo apt install git;
git --version;
sudo snap install docker ;
sudo groupadd docker;
sudo usermod -aG docker $user;
sudo chmod 666 /var/run/docker.sock;
sudo snap install kubectl --classic;
sudo snap install ngrok;
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -;
sudo apt-get install -y nodejs ;
sudo npm install -g generator-jhipster;
